= histric maximal valueのRMQ (遅延評価セグメント木)
:title: {doctitle} - {pagetitle}

histric maximal value (histric information) on Segment Tree with Lazy Propagation

== 概要

以下のクエリが処理できる遅延セグメント木の実装

数列$A = a_1, ..., a_N$ は現在の値、数列$B = b_1, ..., b_N$ は各$a_i$の過去最大値とする。

- $a_i$ の値を $a_i + x$ に更新
- $a_i$ の値を $x$ に更新
- $a_i$ の値を $\max(a_i, x)$ に更新
- $a_l, a_{l+1}, ..., a_{r-1}$ の最大値を求める
- $b_l, b_{l+1}, ..., b_{r-1}$ の最大値を求める

== 実装説明

各ノードのlazy tagとして以下の値を管理することを考える。

- $a_i$ の区間最大値を伝搬するためのlazy tag: $(a, b)$
- $b_i$ の区間最大値を伝搬するためのlazy tag: $(a_H, b_H)$

各tagは、$f_{(a, b)}(x) = \max(x+a, b)$、$h_{(a_H, b_H)}(x) = \max(x + a_H, b_H)$ を計算するための関数のパラメータとする。

lazy tagの初期値は $(0, -\infty)$ になる。
各クエリ操作では以下のtagで更新ノードのlazy tagを更新する。

- $a_i$ を $a_i + x$ に更新するtag: $(x, -\infty)$
- $a_i$ を $x$ に更新するtag: $(-\infty, x)$
- $a_i$ を $\max(a_i, x)$ に更新するtag: $(0, x)$


tag $(c, d)$, $(c_H, d_H)$ の情報を、あるノードのlazy tag $(a, b)$, $(a_H, b_H)$ へマージすることを考える。

この時、ノードが持つtagは以下のように更新できる。

- $(a, b) \leftarrow (a+c, \max(b+c, d))$
- $(a_H, b_H) \leftarrow (\max(a_H, a+c_H), \max(b_H, b+c_H, d_H))$

同時に、子ノードの$a_i$の区間最大値$A$ を $f_{(c, d)}(A)$、$b_i$の区間最大値$B$ を $\max(B, h_{(c_H, d_H)}(A))$ に更新する。

== 計算量

- 各クエリ操作: $O(\log N)$

== 実装

[source, cpp]
----
include::./cpp/range_query/hmv_segment_tree_lp.cpp[]
----

=== Verified

* link:http://uoj.ac/problem/164[UOJ: "#164. 【清华集训2015】V"]: link:http://uoj.ac/submission/348754[source] (C++11, 5393ms)
* link:https://www.lydsy.com/JudgeOnline/problem.php?id=3064[BZOJ: "3064: Tyvj 1518 CPU监控"] (C++, 19328ms)
