= Auxiliary Tree (LCAベース)

Auxiliary Tree, Virtual Tree

== 概要

latexmath:[N] 個の頂点を含む根付き木 latexmath:[T] より、とある頂点集合 latexmath:[X = {v_1, v_2, ..., v_K}] と それらのLCAを含むような木を構築する。

頂点集合 latexmath:[X] に対し、以下の手順によって構築できる。

1. 頂点集合 latexmath:[X] を、グラフ latexmath:[G] をDFSした時のpre-orderの順序で並べる
  - このリストを latexmath:[A = v_{i_1}, v_{i_2}, ..., v_{i_K}] とする
2. latexmath:[1 \le j < K] に対し、 latexmath:[w = lca(v_{i_j}, v_{i_{j+1}})] を求める
3. 頂点集合 latexmath:[X] と(2)のlcaの頂点から、Auxiliary Treeを構築する

ここでは、具体的に以下で構築する

- (2)において、各 latexmath:[1 \le j < K] に対し求めたlca latexmath:[w] をリスト latexmath:[A] に追加する
- リスト latexmath:[A] に含まれる頂点をもう一度pre-orderの順序で並べる
- リスト latexmath:[A] に含まれる頂点 latexmath:[v_i] を走査しながら、stackを用いてリスト latexmath:[A] に含まれる直近の祖先 latexmath:[v_j] を求める

頂点集合 latexmath:[X] のサイズを latexmath:[K] とすると、このAuxiliary Treeの頂点数は高々 latexmath:[2K-1] になる。

== 計算量

Euler Tour TechniqueとSparse Tableを用いた場合

- 前計算: latexmath:[O(N \log N)]
- Auxiliary Treeの構築: latexmath:[O(K \log K)]

Euler Tour TechniqueとSegment Treeを用いた場合

- 前計算: latexmath:[O(N)]
- Auxiliary Treeの構築: latexmath:[O(K (\log K + \log N))]

== 実装 (ETT + Sparse Table)

[source, cpp]
----
include::./cpp/graph/auxiliary_tree.cpp[]
----

=== Verified

* Codeforces: "613D: Kingdom and its Cities": link:https://codeforces.com/contest/613/submission/60606853[source] (C++14, 561ms)
* CodeChef: "ICL2017: Tree Obsession": link:https://www.codechef.com/viewsolution/26228328[source] (C++14, 0.66sec)
