= Dominator (SEMI-NCA Algorithm)

Finding Dominators in Directed Graphs (SEMI-NCA Algorithm)

== 概要

latexmath:[r] を始点とする有向グラフ latexmath:[G = (V, A, r)] において、各頂点 latexmath:[v] を直近で支配する頂点 (an immediate dominator) を求める。

SEMI-NCA では、各頂点 latexmath:[v] の semidominator latexmath:[sdom(v)] を求め、この semidominator を元に徐々に dominator tree を構築する。

各頂点 latexmath:[w] の親頂点 latexmath:[parent(w)] から dominator tree を遡り、 latexmath:[x \le sdom(w)] を満たす初めの頂点 latexmath:[x] を immediate dominator とする。

dominator tree の構築での最悪計算量は latexmath:[O(|V|^2)] になるが、実用的なケースでは高速に動作することが期待できる。 +
(競プロ的には、時間がかかるケースが人為的に生成される可能性がある)

== 計算量

latexmath:[N = |V|], latexmath:[M = |A|] とする

Lengauer-Tarjan Algorithm の simple version の LINK-EVAL を用いて semidominator を構築する場合は latexmath:[O(N^2 + M \log N)]

== 実装

[source, cpp]
----
include::./cpp/graph/dominator-semi-nca.cpp[]
----

=== Verified

* AOJ: "0294: Catch a Thief": link:https://judge.u-aizu.ac.jp/onlinejudge/review.jsp?rid=6495785#1[source] (C++11, 0.17sec)

== 参考

* Georgiadis, Loukas, Robert E. Tarjan, and Renato F. Werneck. "Finding dominators in practice." Journal of Graph Algorithms and Applications 10.1 (2006): 69-94.