before_install:
  - openssl aes-256-cbc -K $encrypted_86f53831cf3d_key -iv $encrypted_86f53831cf3d_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - git config --global user.name "Travis-CI"
  - git config --global user.email "travis-ci@example.com"

language: ruby
install: bundle install --deployment
cache: bundler

script:
  - make docs
  - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash ./deploy.sh'
