= 2-SAT

充足可能性問題 (2-SAT)

== 概要

2-SAT問題を解く。

連言標準形(CNF)形式の論理式をグラフに変換し、強連結成分分解(SCC)を行うことで充足可能性の判定を行う。

=== グラフの構築

latexmath:[N] 個の論理変数 latexmath:[x_1, ..., x_N] を含む論理式について各変数ごとに latexmath:[x_i] と latexmath:[\lnot x_i] を表す latexmath:[2] 個の頂点、全体で latexmath:[2N] 個の頂点を用意する。

論理和 latexmath:[(a \lor b)] を latexmath:[(\lnot a \Rightarrow b) \land (\lnot b \Rightarrow a)] と考え、 latexmath:[\lnot a] から latexmath:[b] への辺 と latexmath:[\lnot b] から latexmath:[a] への辺 を追加する。

この latexmath:[v_0] から latexmath:[v_1] への辺は、 latexmath:[v_0] が真の場合に latexmath:[v_1] も真にする必要があることを表す。

=== 充足可能性の判定

構築したグラフのSCCを求め、各変数 latexmath:[x_i] と latexmath:[\lnot x_i] が同じ強連結成分に含まれていないかを判定する。

=== 論理式を満たす割り当て

強連結成分ごとのトポロジカル順序をもとに論理式が真になる時の各変数の割り当てを決定できる。

トポロジカル順序で latexmath:[\lnot x_i] が latexmath:[x_i] より先にくる場合は latexmath:[x_i] を真、それ以外の場合は偽を割り当てる。

== 計算量

論理変数の数を latexmath:[N], 節の数を latexmath:[M] とした場合 latexmath:[O(N + M)]

== 実装

[source, python]
----
include::./python/graph/2-sat.py[]
----

=== Verified

* yukicoder: "No.274 The Wall": link:https://yukicoder.me/submissions/568812[source] (Python3, 653ms)

== 参考

* 秋葉拓哉, 岩田陽一, and 北川宜稔. "プログラミングコンテストチャレンジブック." (2010).
