= 三角形の外接円/内接円/傍接円
:title: {doctitle} - {pagetitle}

circumcircle, incircle and excircle of a triangle

== 概要

三点 $\mathbf{p_1}, \mathbf{p_2}, \mathbf{p_3}$ から成る三角形の外接円と内接円、傍接円を求める。

ここでは、

$\mathbf{p_1} = (x_1, y_1)$, $\mathbf{p_2} = (x_2, y_2)$, $\mathbf{p_3} = (x_3, y_3)$
$d_1 = \|\mathbf{p_2} - \mathbf{p_3}\|$, $d_2 = \|\mathbf{p_3} - \mathbf{p_1}\|$, $d_3 = \|\mathbf{p_1} - \mathbf{p_2}\|$

と定義する。

=== 外接円 (circumcircle)

各 $i = 1, 2, 3$ の $(x - x_i)^2 + (y - y_i)^2 = r$ から成る連立方程式を計算し、
外接円の中心 $(x, y)$ (= 外心, circumcenter) と 半径 $r$ を求める。

1つの式から別の式を引くと以下の方程式になり $x, y$ を求められる。

$ \displaystyle 2 \left( \begin{array}{cc} x_1 - x_2 & y_1 - y_2 \\ x_1 - x_3 & y_1 - y_3 \end{array} \right) \left( \begin{array}{c} x \\ y \end{array} \right) = \left( \begin{array}{c} (x_1^2 - x_2^2) + (y_1^2 - y_2^2) \\ (x_1^2 - x_3^2) + (y_1^2 - y_3^2) \end{array} \right)$

=== 内接円 (incircle)

内接円の中心 $(x, y)$ (= 内心, incenter) は以下の式で計算できる。

$\displaystyle \left( \frac{d_1 x_1 + d_2 x_2 + d_3 x_3}{d_1 + d_2 + d_3}, \frac{d_1 y_1 + d_2 y_2 + d_3 y_3}{d_1 + d_2 + d_3} \right)$

内接円の半径 $r$ は $\displaystyle \frac{2S}{d_1 + d_2 + d_3}$ で求められる。

=== 傍接円 (excircle)

三角形に対する傍接円は3つあるが、ここでは 辺 $\mathbf{p_2}-\mathbf{p_3}$ に対する傍接円を考える。

この傍接円の中心 $(x, y)$ (= 傍心, excenter) は以下の式で計算できる。

$\displaystyle \left( \frac{- d_1 x_1 + d_2 x_2 + d_3 x_3}{- d_1 + d_2 + d_3}, \frac{- d_1 y_1 + d_2 y_2 + d_3 y_3}{- d_1 + d_2 + d_3} \right)$

また、この傍接円の半径 $r$ は $\displaystyle \frac{2S}{- d_1 + d_2 + d_3}$ で求められる。

== 実装: 外接円

[source, python]
----
include::./python/geometry/triangle_circumcircle.py[]
----

=== Verified

- AOJ: "0010: Circumscribed Circle of a Triangle": link:http://judge.u-aizu.ac.jp/onlinejudge/review.jsp?rid=4435495[source] (Python3, 0.02sec)
- AOJ: "CGL_7_C: Circumscribed Circle of a Triangle": link:http://judge.u-aizu.ac.jp/onlinejudge/review.jsp?rid=5106029#1[source] (Python3, 0.02sec)

== 実装: 内接円と傍接円

[source, python]
----
include::./python/geometry/triangle_incircle_excircle.py[]
----

=== Verified

内接円

- AOJ: "CGL_7_B: Incircle of a Triangle": link:http://judge.u-aizu.ac.jp/onlinejudge/review.jsp?rid=5106019#1[source] (Python3, 0.02sec)

== 参考

- link:https://ja.wikipedia.org/wiki/%E4%B8%89%E8%A7%92%E5%BD%A2%E3%81%AE%E5%86%85%E6%8E%A5%E5%86%86%E3%81%A8%E5%82%8D%E6%8E%A5%E5%86%86[三角形の内接円と傍接円 - Wikipedia]
