= 円同士の交点
:title: {doctitle} - {pagetitle}

== 概要

円1: 中心$(x_1, y_1)$ 半径$r_1$ と 円2: 中心$(x_2, y_2)$ 半径$r_2$ の2つの円について交点を計算する。

円1と円の交点のうちの1点がなす角$\theta$の $\cos \theta$ と $\sin \theta$ の値を計算し、交点の座標を求める。

=== 具体的計算

2つの円の中心同士の距離を$r_0$とし、なす角$\theta$を計算

* $\displaystyle \cos \theta = \frac{r_0^2 + r_1^2 - r_2^2}{2 r_0 r_1}$
* $\displaystyle \sin \theta = \sqrt{1 - \cos^2 \theta} = \frac{\sqrt{4 r_0^2 r_1^2 - (r_0^2 + r_1^2 - r_2^2)^2}}{2 r_0 r_1}$

そして、$d_x = x_2 - x_1$, $d_y = y_2 - y_1$ とすると、2つの交点は、

* $\displaystyle \left( \begin{array}{c} x_1 \\ y_2 \end{array} \right) + \frac{r_1}{r_0} R(\theta) \left( \begin{array}{c} d_x \\ d_y \end{array} \right)$
* $\displaystyle \left( \begin{array}{c} x_1 \\ y_2 \end{array} \right) + \frac{r_1}{r_0} R(-\theta) \left( \begin{array}{c} d_x \\ d_y \end{array} \right)$

で計算できる ($R(\theta)$は$2 \times 2$の回転行列)

=== 頂点から円への接点の計算

応用で 中心 $(x_1, y_1)$ 半径 $r_1$ に対する、点 $(x_2, y_2)$ から引いた接線がなす接点を計算できる。

2点 $(x_1, y_1)$ と $(x_2, y_2)$ の距離を $r_0$ とする時、

この接点は 中心 $(x_1, y_1)$ 半径 $r_1$ と 中心$(x_2, y_2)$ 半径 $\sqrt{r_0^2 - r_1^2}$ の交点を計算することで求まる。

== 実装

[source, python]
----
include::./python/geometry/circle_cross_point.py[]
----

=== Verified

- AOJ: "CGL_7_E: Circles - Cross Points of Circles": link:http://judge.u-aizu.ac.jp/onlinejudge/review.jsp?rid=2416434#1[source] (Python2, 0.01sec)
- AOJ: "2697: Runner and Sniper": link:http://judge.u-aizu.ac.jp/onlinejudge/review.jsp?rid=4896313#1[source] (Python3, 0.03sec)

***
link:../index.html[戻る]