= 点から凸多角形への接線

tangent lines from a point to a convex polygon

== 概要

ある点 latexmath:[w] から凸多角形 latexmath:[P = (v_1, v_2, ..., v_N)] への接線を引いた時に、その接線を通る凸多角形の点 latexmath:[v_i] を求める。

この時、点 latexmath:[w] は凸多角形 latexmath:[P] の外側に存在するとする。

=== 具体的計算

凸多角形 latexmath:[P] 内の適当な点 latexmath:[s] を選ぶ。

latexmath:[h(i)] を 点 latexmath:[w] と latexmath:[s] を通る直線と点 latexmath:[w] と latexmath:[v_i] を通る直線がなす角 (latexmath:[h(i) \in [-\pi, \pi\]]) と定義する。

関数 latexmath:[h] の最大値をとる latexmath:[x] を latexmath:[x_1], 最小値をとる latexmath:[x] を latexmath:[x_0] とする時、
この関数は以下の性質を満たす。

- 区間 latexmath:[[x_0+1, x_0+N-1\]] について 関数 latexmath:[h] は上に凸な関数
- 区間 latexmath:[[x_1+1, x_1+N-1\]] について 関数 latexmath:[h] は下に凸な関数

この最大値と最小値は2回の三分探索で求める。
1回目の三分探索では 区間 latexmath:[[1, N\]] で定義される以下の関数 latexmath:[g] 上で最小値をとる latexmath:[x_0] を求める。(latexmath:[h(1) = h(N)] の場合や latexmath:[h(1)] が極値の場合は特殊ケースとして処理)

latexmath:[\displaystyle g(x) = \min\left(h(x), \frac{h(N) - h(1)}{N-1}(x-1) + h(1)\right)]

2回目の三分探索では 区間 latexmath:[[x_0+1, x_0+N-1\]] 上の関数 latexmath:[h] で latexmath:[x_1] を求める。

この求めた latexmath:[x_0] と latexmath:[x_1] について、点 latexmath:[w] と latexmath:[x_0] を通る直線 と 点 latexmath:[w] と latexmath:[x_1] を通る直線が 点 latexmath:[w] から 凸多角形 latexmath:[P] への接線になる。

== 計算量

latexmath:[O(\log N)]

== 実装

凸多角形の頂点は反時計回りのリストとして持つとする。

[source, python]
----
include::./python/geometry/convex_polygon_tangent.py[]
----

== 参考

* Chazelle, Bernard, and David P. Dobkin. "Intersection of convex objects in two and three dimensions." Journal of the ACM (JACM) 34.1 (1987): 1-27.
