= 中国余剰定理

中国余剰定理 (Chinese remainder theorem)

== 概要

未知の latexmath:[A] について、

- latexmath:[A \equiv X_i] (mod latexmath:[Y_i]) (latexmath:[i = 1, 2, ..., N])

となる latexmath:[X_i] が分かっている時に、

- latexmath:[A \equiv X]  (mod latexmath:[\text{LCM}(Y_1, Y_2, ..., Y_N)])

となる、一意の latexmath:[X] を計算する。

=== 具体的計算

latexmath:[A \equiv a] (mod latexmath:[P]) と latexmath:[A \equiv b] (mod latexmath:[Q]) から latexmath:[A \equiv c] (mod LCM(latexmath:[P], latexmath:[Q])) の値を計算する。

latexmath:[g = \text{gcd}(P, Q)] として、

latexmath:[P x + Q y = g] となる latexmath:[x, y] を拡張ユークリッドの互除法で求める。

そして、(latexmath:[\displaystyle \frac{Q y}{g} \equiv 1 (\text{mod } \frac{P}{g})], latexmath:[\displaystyle \frac{P x}{g} \equiv 1 (\text{mod } \frac{Q}{g}]) が成り立つことを利用して)

latexmath:[\displaystyle c = a \frac{Q y}{g} + b \frac{P x}{g}] (mod LCM(latexmath:[P], latexmath:[Q])) とする。

== 計算量

latexmath:[\displaystyle O(N \log \max_i(Y_i))]

== 実装

[source, python]
----
include::./python/math/chinese-remainder.py[]
----

=== Verified

* yukicoder: "No. 187 中華風 (Hard)": link:https://yukicoder.me/submissions/288619[source] (Python3, 865ms)
* AtCoder: "DISCO presents ディスカバリーチャンネル コードコンテスト2019 予選 - D問題: チップ・ストーリー　〜黄金編〜": link:https://beta.atcoder.jp/contests/ddcc2019-qual/submissions/3649200[source] (Python3, 17ms)
