= 素数mod上の平方根 (Tonelli-Shanks algorithm)

square roots modulo a prime

== 概要

ある奇素数 latexmath:[p] と latexmath:[p] の平方剰余(Quadratic residue) となる latexmath:[y] について latexmath:[x^2 \equiv y] (mod latexmath:[p]) となる latexmath:[x] を求めるアルゴリズム。

=== 具体的な計算

latexmath:[p-1 = 2^mQ] とする。(latexmath:[m \ge 0], latexmath:[Q] は奇数)

まず平方非剰余となる latexmath:[z] を一つ見つける。 (平方非剰余となる数は1からp-1の間に半分は存在する) +
この latexmath:[z] は オイラーの規準(Euler's criterion) より latexmath:[z^\frac{p-1}{2} \equiv z^{2^{m-1}Q} \equiv -1] を満たす。

latexmath:[t \equiv y^Q] とする。この latexmath:[t] はオイラーの規準 より latexmath:[t^{2^{m-1}} \equiv 1] を満たす。

latexmath:[i = m-2] から 0 まで latexmath:[i] を小さくしながら
latexmath:[t^{2^i} \equiv -1] を満たす latexmath:[i] を見つけるたびに latexmath:[t] に latexmath:[z^{2^{m-1-i}Q}] を掛ける。 +
(この時、掛けたあとの latexmath:[t] は latexmath:[t^{2^i} \equiv 1] を満たす)

最終的に latexmath:[t] は latexmath:[\displaystyle t \equiv y^Q z^{2^{j_1}Q} z^{2^{j_2}Q} \cdots z^{2^{j_k}Q} \equiv 1] latexmath:[(1 \le j_1 < j_2 < ... < j_k \le m-1)] の形になるため、 +
latexmath:[\displaystyle x \equiv (ty)^\frac{1}{2} \equiv y^\frac{Q+1}{2} z^{2^{j_1-1}Q} z^{2^{j_2-1}Q} \cdots z^{2^{j_k-1}Q}] を計算することで解が得られる。

== 実装

[source, python]
----
include::./python/math/tonelli-shanks.py[]
----

== 参考

* link:https://en.wikipedia.org/wiki/Tonelli%E2%80%93Shanks_algorithm[Tonelli-Shanks algorithm - Wikipedia]
* 和田秀男. 「コンピュータと素因数分解」. 遊星社, 1987.
