= Binary Indexed Tree

Binary Indexed Tree, BIT, Fenwick Tree

== 概要

部分和と要素の更新のクエリを行う木構造。

配列 latexmath:[a_1, a_2, ..., a_N] を管理するBITは以下のクエリを1回 latexmath:[O(\log N)] で処理できる。

- 部分和 latexmath:[a_1 + a_2 + ... + a_i] を求める
- latexmath:[a_i] に latexmath:[x] を加える

このBITは、以下の操作が行えるデータ構造とも見なすこともできる

- latexmath:[a_i] の値を求める
- latexmath:[a_i, a_{i+1}, ..., a_{N}] に latexmath:[x] を加える

=== BIT の初期化

latexmath:[a_1, a_2, ..., a_N] の初期値が 0 以外の場合を考える。

latexmath:[a_1, a_2, ..., a_k] の和を latexmath:[S_k] と定義する時、以下により latexmath:[O(N)] で初期化できる。

- 各 latexmath:[i = 1, 2, ..., N] について latexmath:[S_k \leftarrow a_k] で初期化
- latexmath:[i = 1] から latexmath:[N] まで順に latexmath:[S_{i + (i\&-i)} \leftarrow S_i + S_{i + (i\&-i)}] で更新

=== 二分探索

latexmath:[a_1 + a_2 + ... + a_i \le x] となる最大の latexmath:[i] は latexmath:[O(\log N)] で計算できる。

== 実装(1次元BIT)

latexmath:[Q] 個のクエリを処理する場合の計算量は latexmath:[O(Q \log N)]

[source, python]
----
include::./python/range_query/bit.py[]
----

クラスを使わない単純な実装

[source, python]
----
include::./python/range_query/bit-simple.py[]
----

=== Verified

* AOJ: "DSL_2_E: Range Query - Range Add Query (RAQ)": link:https://judge.u-aizu.ac.jp/onlinejudge/review.jsp?rid=3158466#1[source] (Python3, 0.77sec)
* AtCoder: "Japan Alumni Group Summer Camp 2017 Day 1 - B問題: リス": link:https://beta.atcoder.jp/contests/jag2017summer-day1/submissions/2559566[source] (PyPy3, 674ms)

== 実装 (2次元BIT)

BITは2次元以上に拡張することができる。

latexmath:[H \times W] の2次元BITにおいて、 latexmath:[Q] 個のクエリを処理する場合の計算量は latexmath:[O(Q \log W \log H)]

[source, python]
----
include::./python/range_query/bit2.py[]
----

== 参考

- link:http://hos.ac/slides/20140319_bit.pdf[Binary Indexed Tree のはなし]
