= RSQ and RAQ (BIT)

Range Sum Query and Range Add Query (RSQ and RAQ)

== 概要

以下のクエリが処理できるBinary Indexed Tree実装

- latexmath:[a_l, a_{l+1}, ..., a_{r-1}] に latexmath:[x] を加算
- latexmath:[a_l, a_{l+1}, ..., a_{r-1}] の和を求める

=== 具体的計算

蟻本ベースの説明footnote:[プログラミングコンテストチャレンジブック [第2版\] p.163]で、Binary Indexed Treeを2つ用いた実装。

latexmath:[P_i = p_1 + ... + p_i], latexmath:[Q_i = q_1 + ... + q_i] として、
latexmath:[a_1, ..., a_i] の和 latexmath:[S_i] を latexmath:[P_i * i + Q_i] と表すことを考える。

こうすると、 latexmath:[a_l, ..., a_{r-1}] の和は latexmath:[S_{r-1} - S_{l-1}] で計算できる。

この時、 latexmath:[a_l, ..., a_{r-1}] に latexmath:[x] を加算したい時、以下の演算により更新できる。

- latexmath:[q_l \leftarrow q_l - x(l-1)]
- latexmath:[q_r \leftarrow q_r + x(r-1)]
- latexmath:[p_l \leftarrow p_l + x]
- latexmath:[p_r \leftarrow p_r - x]

そして、 latexmath:[P_i, Q_i] の値をそれぞれBITで管理することで、加算と和計算の1クエリの計算量を latexmath:[O(\log N)] にすることができる。

== 計算量

- 区間加算: latexmath:[O(\log N)]
- 区間総和: latexmath:[O(\log N)]

== 実装

[source, python]
----
include::./python/range_query/rsq_raq_bit.py[]
----

=== Verified

* AOJ: "DSL_2_G: Range Query - RSQ and RAQ": link:https://judge.u-aizu.ac.jp/onlinejudge/review.jsp?rid=3158675#1[source] (Python3, 1.33sec)
