name: GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for a specific branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # deploy github-pages
  deploy:
    if: github.event.repository.url == 'https://github.com/tjkendev/procon-library'
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Ruby
      - uses: ruby/setup-ruby@v1
        with:
          # ruby-version: 2.6 # read from .ruby-version
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: build pages
        run: make docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          exclude_assets: '.github,src'
